# name: chatacter
# prefix: ./conda
name: base
channels:
    - pytorch
    - nvidia
    - defaults
    - conda-forge
    - 1adrianb
dependencies:
    - python=3.10
    - ffmpeg
    - pytorch=2.1.0
    - torchvision
    - torchaudio
    - pytorch-cuda=12.1
    - imageio=2.19.3
    - imageio-ffmpeg=0.4.7
    - librosa=0.9.2
    - pydub=0.25.1
    - kornia=0.6.8
    - yacs
    - scikit-image=0.19.3
    - facexlib=0.3.0
    - trimesh=3.9.20
    - fastapi
    - huggingface_hub
    - langchain-groq
    - opencv
    - face_alignment=1.3.5
    - transformers
    - pydantic
    - libsndfile
    - accelerate
    - uvicorn
    - optimum
    - pip
    - pip:
          - langchain-community
          - langchain-qdrant
          - basicsr
          - gfpgan
          - wget
          - cog
          - SoundFile
          - opencv-python-headless
          - unstructured[all-docs]
          - fastapi-cli
