[project]
name = "chatacter_backend"
version = "0.1.0"
description = "Add a short description here"
authors = ["Mohamed Hisham Abdelzaher <mohamed.hisham.abdelzaher@gmail.com>"]
channels = ["pytorch", "nvidia", "conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "==3.10"
pytorch = "2.1.0.*"
torchvision = ">=0.16.0,<0.17"
torchaudio = ">=2.1.0,<2.2"
pytorch-cuda = "12.1.*"

[pypi-dependencies]
absl-py = "*"
addict = "*"
altair = "*"
annotated-types = "*"
anyio = "*"
attrs = "*"
audioread = "*"
av = "*"
basicsr = "*"
blinker = "*"
cachetools = "*"
certifi = "*"
cffi = "*"
charset-normalizer = "*"
click = "*"
cog = "*"
contourpy = "*"
cryptography = "*"
cycler = "*"
decorator = "*"
distro = "*"
exceptiongroup = "*"
face-alignment = "*"
facexlib = "*"
fastapi = "*"
filelock = "*"
filterpy = "*"
fonttools = "*"
fsspec = "*"
future = "*"
gfpgan = "*"
gitdb = "*"
gitpython = "*"
groq = "*"
grpcio = "*"
h11 = "*"
httpcore = "*"
httptools = "*"
httpx = "*"
huggingface-hub = "*"
idna = "*"
imageio = "*"
imageio-ffmpeg = "*"
importlib-metadata = "*"
jinja2 = "*"
joblib = "*"
jsonpatch = "*"
jsonpointer = "*"
jsonschema = "*"
jsonschema-specifications = "*"
kiwisolver = "*"
kornia = "*"
langchain-groq = "*"
langsmith = "*"
librosa = "*"
llvmlite = "*"
lmdb = "*"
markdown = "*"
markdown-it-py = "*"
markupsafe = "*"
matplotlib = "*"
mdurl = "*"
mpmath = "*"
networkx = "*"
numba = "*"
numpy = "*"
opencv-python = "*"
orjson = "*"
pandas = "*"
pillow = "*"
platformdirs = "*"
pooch = "*"
protobuf = "*"
pyarrow = "*"
pycparser = "*"
pydantic = "*"
pydeck = "*"
pydub = "*"
pygments = "*"
pyparsing = "*"
python-dateutil = "*"
pytz = "*"
pywavelets = "*"
pyyaml = "*"
referencing = "*"
regex = "*"
requests = "*"
resampy = "*"
rich = "*"
rpds-py = "*"
ruff = "*"
safetensors = "*"
scikit-image = "*"
scikit-learn = "*"
scipy = "*"
setuptools = "*"
six = "*"
smmap = "*"
sniffio = "*"
soundfile = "*"
starlette = "*"
structlog = "*"
sympy = "*"
tb-nightly = "*"
tenacity = "*"
tensorboard-data-server = "*"
threadpoolctl = "*"
tifffile = "*"
tokenizers = "*"
toml = "*"
tomli = "*"
toolz = "*"
tornado = "*"
tqdm = "*"
transformers = "*"
triton = "*"
typing-extensions = "*"
tzdata = "*"
urllib3 = "*"
uvloop = "*"
watchdog = "*"
watchfiles = "*"
websockets = "*"
werkzeug = "*"
wget = "*"
wheel = "*"
yacs = "*"
yapf = "*"
zipp = "*"
sentry-sdk = "*"

[feature.fastapi.pypi-dependencies]
sentry-sdk = "*"
