[project]
name = "backend"
version = "0.1.0"
description = "Add a short description here"
authors = ["Mohamed Hisham Abdelzaher <mohamed.hisham.abdelzaher@gmail.com>"]
channels = ["pytorch", "nvidia", "conda-forge"]
platforms = ["linux-64", "win-64"]

[tasks]

[dependencies]
python = "==3.10"
numpy = "<1.23"
pytorch = "<=2.1.0"
torchvision = ">=0.16.0,<0.17"
torchaudio = ">=2.1.0,<2.2"
pytorch-cuda = "==12.1"
ffmpeg = ">=4.3,<5"
uvicorn = ">=0.30.0,<0.31"
fastapi = ">=0.111.0,<0.112"
setuptools = "<60.0"
safetensors = ">=0.4.3,<0.5"
imageio = "==2.19.3"
imageio-ffmpeg = "==0.4.7"
librosa = "==0.9.2"
resampy = "==0.3.1"
scipy = ">=1.13.1,<1.14"
llvmlite = "==0.38.1"
joblib = ">=1.4.2,<1.5"
pydub = "==0.25.1"
kornia = "==0.6.8"
yacs = "==0.1.8"
scikit-image = "==0.19.3"
python-dateutil = ">=2.9.0,<2.10"
pip = ">=24.0,<25"
pandas = ">=2.2.2,<2.3"
pytz = ">=2024.1,<2025"
pyparsing = ">=3.1.2,<3.2"
six = ">=1.16.0,<1.17"
certifi = ">=2024.2.2,<2024.3"
huggingface_hub = ">=0.23.2,<0.24"
langchain-core = ">=0.2.3,<0.3"
langchain-groq = ">=0.1.4,<0.2"
transformers = ">=4.41.2,<4.42"

[pypi-dependencies]
gfpgan = "*"
wget = "*"
opencv-python = "*"
face-alignment = { version = "==1.3.5" }
facexlib = { version = "==0.3.0" }
sentry-sdk = "*"
