target-version = "py311"
output-format = "github"

[format]
indent-style = "tab"
docstring-code-format = true

[lint]
select = ["F", "B", "W", "Q", "E", "RUF"]
ignore = ["W191"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.isort]
length-sort = true