target-version = "py311"
output-format = "github"

[lint]
select = ["E4", "E7", "E9", "F", "B", "W"]
ignore = ["W191"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
indent-style = "tab"
docstring-code-format = true
