[project]
name = "App"
description = "Backend Part of Chatacter"
channels = ["conda-forge"]
platforms = ["linux-64"]

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu121"]

[dependencies]
python = "3.10.*"
langchain-groq = ">=0.1.6,<0.2"
langchain = ">=0.2.11,<0.3"
langchain-community = ">=0.2.10,<0.3"
fastapi = ">=0.111.1,<0.112"
fastapi-cli = ">=0.0.4,<0.0.5"

[pypi-dependencies]
unstructured = {version = ">=0.15.0, <0.16", extras = ["all-docs"]}
qdrant-client = {version = ">=1.0.1, <2", extras = ["fastembed-gpu"]}
