# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
    # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
    secret_key: "b3833274b79dc10d4a49167a50d14419e3dc32092a3d8d876081db2419bff392" # change this!
    limiter: false
    image_proxy: true
    method: "GET"
ui:
    static_use_hash: true
redis:
    url: redis://redis:6379/0
