name: Lint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  checks: write
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: code_quality
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Lint Docker Compose files
        uses: docker-compose-linter/dclint-github-action@v1.5.0
        with:
          path: ./compose.yaml
          fix: true
      - name: Commit and push applied linter fixes
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
        if: success() || failure()
        with:
          commit_message: "[Trunk] Apply linters fixes"
