name: Create and publish a Docker image
on:
    pull_request:
    push:
        branches: ["main"]
env:
    REGISTRY: ghcr.io
    IMAGE_NAME_APP: ${{ github.repository }}_app
    IMAGE_NAME_VIDEO_GENERATOR: ${{ github.repository }}_video_generator
    IMAGE_NAME_VOICE_GENERATOR: ${{ github.repository }}_voice_generator
jobs:
    AppImage:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@master
            - name: Log in to the Container registry
              uses: docker/login-action@master
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.TOKEN_KEY_GITHUB }}
            - name: Extract metadata (tags, labels) for Docker for App
              id: meta
              uses: docker/metadata-action@master
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_APP }}
                  tags: |
                      type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
                      type=raw,value={{branch}},enable=${{ github.ref != format('refs/heads/{0}', 'main') }}
            - name: Build and push App Docker image
              id: push
              uses: docker/build-push-action@master
              with:
                  context: ./App
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  github-token: ${{ secrets.TOKEN_KEY_GITHUB }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
            - name: Generate artifact attestation for App
              uses: actions/attest-build-provenance@v1
              with:
                  subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_APP }}
                  subject-digest: ${{ steps.push.outputs.digest }}
                  push-to-registry: true
    VideoGeneratorImage:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@master
            - name: Log in to the Container registry
              uses: docker/login-action@master
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.TOKEN_KEY_GITHUB }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@master
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_VIDEO_GENERATOR }}
                  tags: |
                      type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
                      type=raw,value={{branch}},enable=${{ github.ref != format('refs/heads/{0}', 'main') }}
            - name: Build and push Video Generator Docker image
              id: push
              uses: docker/build-push-action@master
              with:
                  context: ./VideoGenerator
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  github-token: ${{ secrets.TOKEN_KEY_GITHUB }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
            - name: Generate artifact attestation for Video Generator
              uses: actions/attest-build-provenance@main
              with:
                  subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_VIDEO_GENERATOR }}
                  subject-digest: ${{ steps.push.outputs.digest }}
                  push-to-registry: true
    VoiceGeneratorImage:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@master
            - name: Log in to the Container registry
              uses: docker/login-action@master
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.TOKEN_KEY_GITHUB }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@master
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_VOICE_GENERATOR }}
                  tags: |
                      type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
                      type=raw,value={{branch}},enable=${{ github.ref != format('refs/heads/{0}', 'main') }}
            - name: Build and push Voice Generator Docker image
              id: push
              uses: docker/build-push-action@master
              with:
                  context: ./VoiceGenerator
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  github-token: ${{ secrets.TOKEN_KEY_GITHUB }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
            - name: Generate artifact attestation for Voice Generator
              uses: actions/attest-build-provenance@main
              with:
                  subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_VOICE_GENERATOR }}
                  subject-digest: ${{ steps.push.outputs.digest }}
                  push-to-registry: true
